### PR TITLE
Chrome 62 fix: Parse 'raw' requestBody if 'formData' isn't available.

### PR DESCRIPTION
**Pull request by bdruth**
Per #6, Chrome 62 isn't providing a pre-parsed ``formData`` object to retrieve the ``SAMLResponse``. Parse the ``raw`` ArrayBuffer data to retrieve the ``SAMLResponse`` payload and other ``formData`` params.

### CODE REVIEW

**Comment by piascikj** [comment]
👍

**Comment by bdruth** [comment]
Created https://bugs.chromium.org/p/chromium/issues/detail?id=777898 so that the Chromium team is aware of this change in behavior (which seems buggy to me, not intentional).

**Comment by dubharmonic** [comment]
👍

**Comment by prolane** [comment]
@bdruth Thanks for reporting! My apologies for my late reply. I'll have a look at the code, test, merge and update the Chrome plugin asap. Will be somewhere this week.

**Comment by prolane** [comment]
Code looks good. Thanks again for contributing and thanks for using the extension!

**Pull request merged**
