### PR TITLE
Remove extraneous spaces prior to newline.

### LINKED ISSUE #14: Remove the inserted space before all Line Feeds (LF)
Each line in the credentials-file, has a space inserted before the LF. Please trim before inserting the headers and values into the file. Otherwise, you need to cleanup these spaces, when trying to read the file as an "ini-file".

### PR DESCRIPTION
**Pull request by ashemedai**
Closes #14

### CODE REVIEW

**Comment by ashemedai** [comment]
@prolane Was there any reason for those extraneous spaces?

**Comment by prolane** [comment]
@ashemedai Don't know for sure. I think there was, it's just a long time ago. I'm thinking it had something to do with how the credentials file came out on Windows systems. I don't have a Windows system around right now to test. I could test this later on a VM.

**Comment by ashemedai** [comment]
@prolane Got a few other small changes I am also making in this area to work towards solving the larger issue with the errors returned from AWS. And in the process I found out just how badly I suck at the JavaScript mindset of programming (as in every time I am close to have a functionality working, it's like: ha HA, that's not how it behaves).

**Comment by nitrocode** [comment]
Hi @prolane. great extension! 

@ashemedai nice fix. is this ready to be merged?

**Comment by ashemedai** [comment]
@nitrocode Yes, should still be good.

**Comment by nitrocode** [comment]
Awesome.

@prolane do you mind merging? 😄

**Comment by prolane** [comment]
I'm pretty sure those spaces were there for a reason. I've tested this branch on Windows. The aws cli works (I guess the cli just reads LF). But if you check the credentials file, everything is on one line and not seperated (because you can't see the LF as its not space and not a CRLF).

Even though it seems it still works (at least the aws cli does) I decided to do it right and implement a fix for Windows users as well. This means it fixes #21 as well.

#14 and #21 are fixed in release v2.5
https://github.com/prolane/samltoawsstskeys/commit/21f4738cdd9e4e8b13a77973e1f19a12aec6c0f8

Nevertheless, thanks for your contribution @ashemedai 👍

**Pull request closed without merging**
